{
    'name': 'Gestion de Parc Informatique',
    'version': '18.0.1.0.0',
    'category': 'Technical',
    'author': 'TECHPARK CI - IIT Grand-Bassam',
    'website': 'https://techpark-ci.com',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'hr',
        'stock',
        'purchase',
        'account',
        'maintenance',
        'mail',
        'contacts',
        'web',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'data/it_parc_demo.xml',
        'views/it_menus.xml',
        'views/it_equipment_views.xml',
        'views/it_affectation_views.xml',
        'views/it_intervention_views.xml',
        'views/it_contract_views.xml',
        'views/it_alert_views.xml',
        'views/it_dashboard_views.xml',
        'report/it_equipment_report.xml',
        'report/it_inventory_report.xml',
        'report/it_maintenance_report.xml',
        'wizards/it_affectation_wizard_views.xml',
        'wizards/it_import_wizard_views.xml',
        'wizards/it_contract_renewal_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'it_parc/static/src/js/it_dashboard.js',
            'it_parc/static/src/css/it_dashboard.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
